# Generated by Django 5.1.7 on 2025-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
